name: ash_app
description: ssh - AI Scheduling Helper mobile and web app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3

  # HTTP & API (REMOVED DUPLICATE)
  http: ^1.2.2
  dio: ^5.4.0
  web_socket_channel: ^3.0.1

  # Authentication
  google_sign_in: ^7.2.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.2
  flutter_facebook_auth: ^7.1.1

  # Voice & Speech
  flutter_tts: ^4.0.2
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  avatar_glow: ^3.0.1

  # UI Components
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1

  # Calendar & Date
  intl: ^0.20.2
  table_calendar: ^3.2.0
  syncfusion_flutter_calendar: ^31.1.23

  # Storage & Preferences
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Web Support
  webview_flutter: ^4.4.2

  # Utilities
  uuid: ^4.3.3
  logger: ^2.0.2+1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.1.0

  # Audio & Media
  audioplayers: ^6.5.1
  record: ^6.1.2

  # Animations
  lottie: ^3.3.2
  animations: ^2.0.8
  firebase_core: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0  
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true